#!/usr/bin/env bash
set -euo pipefail

# Stage 4A command plan. Review and run commands manually.
# Set PFC_CUDA_DEVICES before running, for example: export PFC_CUDA_DEVICES=0
cd /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache

CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/run_jit_stage4a_generate.py --method no_cache_50 --num-images 50000 --batch-size 8 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/run_jit_stage4a_generate.py --method bfc_quality_t02_08 --num-images 50000 --batch-size 8 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/run_jit_stage4a_generate.py --method bfc_speed_t02_10 --num-images 50000 --batch-size 8 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/run_jit_stage4a_generate.py --method reduced_steps_35 --num-images 50000 --batch-size 8 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/run_jit_stage4a_generate.py --method reduced_steps_30 --num-images 50000 --batch-size 8 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n deco python scripts/run_deco_stage4a_generate.py --method no_cache_50 --num-images 50000 --batch-size 4 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n deco python scripts/run_deco_stage4a_generate.py --method bfc_all_candidates_t02_10 --num-images 50000 --batch-size 4 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n deco python scripts/run_deco_stage4a_generate.py --method bfc_backbone_plus_final_t02_10 --num-images 50000 --batch-size 4 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n deco python scripts/run_deco_stage4a_generate.py --method reduced_steps_35 --num-images 50000 --batch-size 4 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n deco python scripts/run_deco_stage4a_generate.py --method reduced_steps_30 --num-images 50000 --batch-size 4 --seed 0 --run-id stage4a_n50000_seed0 --output-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --save-png --no-save-npz --resume

# FID/IS evaluation commands. Run after generation completes.
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/jit/stage4a_n50000_seed0/no_cache_50/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/jit/no_cache_50/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/jit/stage4a_n50000_seed0/bfc_quality_t02_08/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/jit/bfc_quality_t02_08/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/jit/stage4a_n50000_seed0/bfc_speed_t02_10/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/jit/bfc_speed_t02_10/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/jit/stage4a_n50000_seed0/reduced_steps_35/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/jit/reduced_steps_35/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/jit/stage4a_n50000_seed0/reduced_steps_30/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/jit/reduced_steps_30/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/deco/stage4a_n50000_seed0/no_cache_50/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/deco/no_cache_50/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/deco/stage4a_n50000_seed0/bfc_all_candidates_t02_10/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/deco/bfc_all_candidates_t02_10/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/deco/stage4a_n50000_seed0/bfc_backbone_plus_final_t02_10/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/deco/bfc_backbone_plus_final_t02_10/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/deco/stage4a_n50000_seed0/reduced_steps_35/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/deco/reduced_steps_35/fid_results.json
CUDA_VISIBLE_DEVICES=${PFC_CUDA_DEVICES:-0} conda run -n jit python scripts/evaluate_stage4a_fid.py --fake-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation/deco/stage4a_n50000_seed0/reduced_steps_30/images --fid-stats third_party/JiT/fid_stats/jit_in256_stats.npz --backend auto --metrics fid,is --batch-size 64 --out /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid/stage4a_n50000_seed0/deco/reduced_steps_30/fid_results.json

# Summarize after FID JSON files are written.
conda run -n jit python scripts/collect_stage4a_fid_results.py --root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/outputs/stage4a/full_generation --fid-root /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/fid --out-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/summary/stage4a_n50000_seed0
conda run -n jit python scripts/plot_stage4a_full_eval.py --summary-dir /mnt/iset/nfs-main/private/zhuangyifan/PixelFlowCache/logs/stage4a/summary/stage4a_n50000_seed0
